"""Crear tabla de Maestros

Revision ID: af412cbc6815
Revises: 
Create Date: 2026-02-27 18:04:44.822511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af412cbc6815'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_diario_rentas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_diario_rentas',
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('ingresos_totales', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('peliculas_rentadas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fecha'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
